- name: Install RKE2 server
  hosts: ~rke2-master-[1-2]
  become: true
  vars_files:
    - env_vars.yaml
    - token

  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
      recurse: yes
    loop:
      - "/etc/rancher/rke2"
      - "/var/lib/rancher/rke2/server/manifests"

  - name: Create the config.yaml file
    copy:
      dest: "/etc/rancher/rke2/config.yaml"
      content: |
        token: {{ TOKEN }}
        server: https://{{ API_DOMAIN }}:9345
        tls-san:
          - "{{ ansible_ssh_host }}"
          - "{{ API_DOMAIN }}"
          - "{{ KUBE_VIP_ADDRESS }}"
        cni: "cilium"
        etcd-snapshot-schedule-cron: "0 */4 * * *"
        etcd-snapshot-retention: 10
        disable:
          - rke2-canal
          - rke2-ingress-nginx
      owner: root
      group: root
      mode: 0644
      
  - name: Install RKE server
    shell: |
      curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=stable INSTALL_RKE2_VERSION="{{ RKE2_VERSION }}" sh -
  
  - name: Start rke2-server service
    ansible.builtin.service:
      name: rke2-server
      state: started
  
  - name: Enable rke2-server service
    ansible.builtin.systemd:
      name: rke2-server
      enabled: yes