- name: Install RKE2 agent
  hosts: ~rke2-worker-[0-5],~rke2-infra-[0-2]
  become: true
  vars_files:
    - env_vars.yaml
    - token

  tasks:
  - name: Create directory
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
      recurse: yes
    loop:
      - "/etc/rancher/rke2"

  - name: Create the config.yaml file
    copy:
      dest: "/etc/rancher/rke2/config.yaml"
      content: |
        token: {{ TOKEN }}
        server: https://{{ API_DOMAIN }}:9345
        
  - name: Install RKE2 agent
    shell: |
      curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=stable INSTALL_RKE2_VERSION="{{ RKE2_VERSION }}" sh -

  - name: Start rke2-agent service
    ansible.builtin.service:
      name: rke2-agent
      state: started
  
  - name: Enable rke2-agent service
    ansible.builtin.systemd:
      name: rke2-agent
      enabled: yes
