- name: Upgrade RKE2 server
  hosts: ~rke2-master-[0-2]
  become: true
  vars_files:
    - env_vars_upgrade.yaml 

  tasks:
  - name: Install RKE2 server
    shell: |
      curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="{{ RKE2_VERSION }}" sh -

  - name: Restart rke2-server service
    ansible.builtin.service:
      name: rke2-server
      state: restarted